name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.0
  dart_openai:
    path: ../
  envied: ^0.3.0
  http: ^0.13.6

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  lints: ^2.0.0
  test: ^1.16.0
